Install latest plotly and kaleido on both Ubuntu and Debian base images.
Unfortunately this requires installing Google Chrome (instead of Chromium) on Ubuntu, because upstream support for automatically installing Chromium is lacking in both Ubuntu and in the automated browser installation tool by plotly.

Some tolerances related to plotly image comparison needed to be tweaked, because the fonts and the image sizes are slightly different in the two browser implementations.

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -28,7 +28,7 @@ RUN set -e; \
             ;; \
     esac
 
-# Update package lists and install required packages, then clean cache
+# Install required apt packages
 RUN apt update -y -q && \
     # Install basic commands
     apt install -y -qq --no-install-recommends git patch && \
@@ -36,10 +36,6 @@ RUN apt update -y -q && \
     apt install -y -qq --no-install-recommends texlive-extra-utils texlive-humanities texlive-latex-extra texlive-lang-english texlive-science; \
     # Install additional required LaTeX related packages
     apt install -y -qq --no-install-recommends latexmk poppler-utils && \
-    # Install chromium for kaleido
-    if apt-cache policy chromium | grep Candidate | grep -v '(none)' >/dev/null 2>&1; then \
-        apt install -y -qq --no-install-recommends chromium chromium-driver; \
-    fi && \
     # Install fonts for plotly
     apt install -y -qq --no-install-recommends fonts-noto && \
     # Install required Python packages via apt
@@ -77,11 +73,38 @@ RUN patch -p0 < /tmp/drop_tikz_semicolons.patch && rm /tmp/drop_tikz_semicolons.
 # Update LuaTeX font database
 RUN luaotfload-tool -u
 
-# Install required Python packages via pip with no cache
+# Install required Python packages via pip
 RUN export PIP_BREAK_SYSTEM_PACKAGES=1 && \
     python3 -m pip install --no-cache-dir ImageHash nbdime nbval pandas pillow sympy && \
-    if command -v chromium >/dev/null 2>&1; then \
-        python3 -m pip install --no-cache-dir kaleido plotly; \
-    else \
-        python3 -m pip install --no-cache-dir "kaleido<1.0.0" "plotly<6.2.0"; \
-    fi
+    python3 -m pip install --no-cache-dir kaleido plotly
+
+# Install chromium (in debian) or chrome (in ubuntu) for kaleido
+RUN apt update -y -q && \
+    # Determine the base image and install the appropriate browser:
+    # Debian supports apt installable chromium and chromium-driver packages,
+    # and therefore we use them.
+    # Ubuntu has chromium-browser and chromium-chromedriver package, but they
+    # actually require snap packages to work. In principle we could have let
+    # plotly install its own version of chrome via plotly_get_chrome, but
+    # their script does not automatically install the required apt depencies,
+    # rendering the installed browser uselss. For this reason, we install
+    # Google Chrome instead of chromium, even though using the proprietary
+    # implementation must be interpreted as a last resort and temporary
+    # workaround until upstream projects provide better installation support.
+    case "$BASE_IMAGE" in \
+        *ubuntu*) \
+            apt install -y -qq --no-install-recommends wget && \
+            wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/google-chrome.deb && \
+            apt install -y -qq --no-install-recommends /tmp/google-chrome.deb && \
+            rm /tmp/google-chrome.deb; \
+            ;; \
+        *debian*) \
+            apt install -y -qq --no-install-recommends chromium chromium-driver; \
+            ;; \
+        *) \
+            echo "Invalid base image: $BASE_IMAGE. Please use a supported Debian or Ubuntu base image."; \
+            exit 1; \
+            ;; \
+    esac && \
+    # Clean cache
+    apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
